module.exports = {
    STATUS_CODE: [401, 400, 403, 500],
    STATUS_ERROR: ['INVALID_TOKEN', 'AUTHENTICATION_FAILURE', 'MANDATORY_NOT_FOUND', 'DUPLICATE_DATA', 'LIMIT_EXCEEDED', 'AUTHORIZATION_FAILED', 'NO_PERMISSION', 'INTERNAL_ERROR'],
    SUPPORT_REQUEST: {
        COMMENT: "Comment",
        NEW_TICKET: "New Ticket"
    },
    REFRESH_TOKEN: "refresh_token"
}

